<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Zero1\Editors\Elf\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Be.Windows.Forms.HexBox.Net5" Version="1.8.0" />
    <PackageReference Include="SharpGLTF.Core" Version="1.0.5" />
    <PackageReference Include="SharpGLTF.Toolkit" Version="1.0.5" />
  </ItemGroup>

</Project>